schema: "1"
pipeline:
  application: reactuiboilerplate
  name: reactuiboilerplate-feature-build
  template:
    source: spinnaker://BuildTemplateFeatureV1
  variables:
    microserviceName: reactuiboilerplate
    minCPU: 0.1
    maxCPU: 2
    minMemory: 512Mi
    maxMemory: 2048Mi
    minNumberOfReplicas: 1
    maxNumberOfReplicas: 2
    cpuUtilizationTargetForAutoScaling: 60
    livelinessURL: reactuiboilerplate/v1/health
    TeamName: teamname
    TeamDL: teamDL@volvocars.com
    args: npm run start
    uiFunctionalTest: true
    uiPerfTest: true
    loadTest: true
    secrets:
    - name: team-backend-instance-1
      envVars:
      - backend_username
      - backend_password    
    configMaps:
    - name: reactuiboilerplate-config
      subPath: app
    envVariables:
    - name: ENV_CONFIG_FILE_PATH
      value: /deployments/config
configuration:
  inherit:
  - triggers
  - expectedArtifacts
  - stages
  - parameters
